sudo: required
language: python
services:
- docker
stages:
- test
- name: deploy
  if: branch = develop

env:
- distro=alpine
- distro=ubuntu

install:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo sh -c 'echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release
  -cs) stable" > /etc/apt/sources.list.d/docker.list'
- sudo apt-get update -o Dir::Etc::sourcelist=/etc/apt/sources.list.d/docker.list
- sudo apt-get -y install docker-ce
- sudo curl -fsSL https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname
  -s`-`uname -m` -o /usr/local/bin/docker-compose
- sudo chmod +x /usr/local/bin/docker-compose
- docker version
- docker-compose version
script:
- .travis/test.sh

jobs:
  include:
    - stage: deploy
      env:
      - 
      install: true
      script:
      - .travis/deploy.sh

branches:
  except:
  - master
  - X-archive
notifications:
  slack:
    rooms:
      secure: OC8BIRtvReJ4AWXg1Hc6lLulTk+N4V1BUD9u7P0J21Z47DSN9mEi7Or0qZtKZIGuTiTv8K9IAmi0AF2xoztU3myJSdwre2tZFzXhtIZwGIIOryQTrhdbE9Rg3l0UVOTZ6gDLtBI2ttZ6ZadI0GkVPO69csH4usMiKLufCKd34XZDzClrsNJjKWsQc1Y3fGOyRLy/NhDWTfPYHB033El73JQogaGhLg5UhLoz0/laFAUI9FadNFtY5rsWqoEVzFWZSNmPH//j4+WoeunyPJNNRNhQORBO2iDd8fkxTuZxyQPX6H6o9BVeaJvnHtpu5+tzTetPh0V3D+JDbGwdzx/rvWGbDB9n/3ebgzUZdbYTZ6x1YSxiIpPjAgTYBrxZWAx8imw5bjlPbdwTzDsryHKcmOyG8ISaUHTiaiVYHcDqvo7fSYqCDAOAYL3KmhECMZDcCFDpyIfK7hiitB4Ki5qZ4mjuEn6bytQsmv2zE2OYK9kjKAEn5DChqISyXOYRuCeESOc2+7Y2Bq2zsd5C/Q1w1WDAGWIKideF5/+z1ye1Pub7MblV1nSGmg05knnXsnqNUShk1v1dvgcvTVpB6aEhJY1HZmXixeb9v0RB14q1t6V3pa7hJlUTotwjIc8U0UG1q8JVMGV+0idkksP+ax5a9QzMEnXUv451sXeczPveQa8=
  on_success: always
  on_failure: always

