version: '3.3'
services:
  saltmaster:
    hostname: salt
    build: ../ubuntu/
    ports:
      - 4505:4505
      - 4506:4606
      - 8000:8000
    ulimits:
      nofile: 10000
    volumes:
      - type: bind
        source: ./_config
        target: /srv/etc/salt/master.d
        read_only: true
      - type: bind
        source: ./salt
        target: /srv/salt
        read_only: true
#    cap_drop:
#      - CAP_CHOWN
#      - CAP_NET_BIND_SERVICE
#      - CAP_SYS_BOOT
#      - CAP_SYS_TIME
