version: '3.3'
services:
  saltmaster:
    hostname: salt
    build: ../ubuntu
    #env_file:
    expose:
      - 4505
      - 4506
    ports:
      - 8000:8000
    ulimits:
      nofile: 10000
    volumes:
      - type: bind
        source: ./_config
        target: /srv/etc/salt/master.d
        read_only: true
      - type: bind
        source: ./salt
        target: /srv/salt
        read_only: true
      - type: bind
        source: ./minion/_config/minion
        target: /etc/salt/minion
        read_only: true
      - type: volume
        source: saltmaster-pki
        target: /srv/etc/salt/pki/
  saltminion:
    hostname: minion
    image: travis_saltmaster
    #build: minion
    ulimits:
      nofile: 10000
    expose: []
    volumes:
      - type: bind
        source: ./minion/_config/minion
        target: /etc/salt/minion
      - type: volume
        source: saltminion-pki
        target: /srv/etc/salt/pki/
    entrypoint: ["tini", "-g", "--", "salt-minion"]
    links:
      - saltmaster:salt
    depends_on:
      - saltmaster
#cap_drop:
#  - CAP_CHOWN
#  - CAP_NET_BIND_SERVICE
#  - CAP_SYS_BOOT
#  - CAP_SYS_TIME
volumes:
  saltmaster-pki:
  saltminion-pki:
