version: '3.3'
services:
  saltminion:
    hostname: minion
    image: digitalr00ts/saltstack
    ulimits:
      nofile: 10000
    #volumes:
    #  - type: bind
    #    source: ./_config
    #    target: /srv/etc/salt/master.d
    #    read_only: true
    #  - type: bind
    #    source: ./salt
    #    target: /srv/salt
    #    read_only: true
    external_links:
      - travis_saltmaster_1:salt
#    cap_drop:
#      - CAP_CHOWN
#      - CAP_NET_BIND_SERVICE
#      - CAP_SYS_BOOT
#      - CAP_SYS_TIME
